broadview-es:
  hostname: 100.98.133.128
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.0.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.0.0.0 255.255.0.0
          next_hop: 10.43.3.10
      - name: vlan100
        type: vlan
        ip: 192.168.0.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
campora-fam-resctr:
  hostname: 100.98.133.129
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.44.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.11.0.0 255.255.0.0
          next_hop: 10.43.47.10
      - name: vlan100
        type: vlan
        ip: 192.168.44.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
clark-memorial-es:
  hostname: 100.98.133.130
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.4.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.1.0.0 255.255.0.0
          next_hop: 10.43.7.71
      - name: vlan100
        type: vlan
        ip: 192.168.4.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
cowan-es:
  hostname: 100.98.133.131
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.36.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.9.0.0 255.255.0.0
          next_hop: 10.43.39.10
      - name: vlan100
        type: vlan
        ip: 192.168.36.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
dechard-es:
  hostname: 100.98.133.132
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.40.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.10.0.0 255.255.0.0
          next_hop: 10.43.43.10
      - name: vlan100
        type: vlan
        ip: 192.168.40.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
franklin-co-alt-svc:
  hostname: 100.98.133.133
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.52.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.13.0.0 255.255.0.0
          next_hop: 10.43.55.10
      - name: vlan100
        type: vlan
        ip: 192.168.52.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
franklin-co-dist-bldg:
  hostname: 100.98.133.135
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.60.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.4.0.0 255.255.0.0
          next_hop: 10.43.63.10
      - name: vlan100
        type: vlan
        ip: 192.168.60.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
franklin-co-hs:
  hostname: 100.98.133.134
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.12.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.3.0.0 255.255.0.0
          next_hop: 10.43.12.10
      - name: vlan100
        type: vlan
        ip: 192.168.12.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
huntland-sch:
  hostname: 100.98.133.136
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.20.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.5.0.0 255.255.0.0
          next_hop: 10.43.23.11
      - name: vlan100
        type: vlan
        ip: 192.168.20.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
north-lake-es:
  hostname: 100.98.133.137
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.48.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.12.0.0 255.255.0.0
          next_hop: 10.43.51.10
      - name: vlan100
        type: vlan
        ip: 192.168.48.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
north-ms:
  hostname: 100.98.133.138
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.8.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.2.0.0 255.255.0.0
          next_hop: 10.43.11.10
      - name: vlan100
        type: vlan
        ip: 192.168.8.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
rock-creek-es:
  hostname: 100.98.133.139
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.24.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.6.0.0 255.255.0.0
          next_hop: 10.43.27.42
      - name: vlan100
        type: vlan
        ip: 192.168.24.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
sewanee-es:
  hostname: 100.98.133.140
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.28.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.7.0.0 255.255.0.0
          next_hop: 10.43.31.23
      - name: vlan100
        type: vlan
        ip: 192.168.28.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
south-ms:
  hostname: 100.98.133.141
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.32.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.8.0.0 255.255.0.0
          next_hop: 10.43.35.10
      - name: vlan100
        type: vlan
        ip: 192.168.32.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True
tech-ctr:
  hostname: 100.98.133.142
  groups:
    - fortigates
  data:
    interfaces:
      - name: x1
        ip: 10.43.16.1
        mask: 255.255.252.0
        description: ::LAN
        route_down: 
        - dest: 10.14.0.0 255.255.0.0
          next_hop: 10.43.19.10
      - name: vlan100
        type: vlan
        ip: 192.168.16.1
        mask: 255.255.255.0
        description: Voice
        build_dhcp_server: True